version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for a simple HTML project."
  pre_build:
    commands:
      - echo "Starting the build process..."
  build:
    commands:
      - echo "Building the HTML project..."
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  base-directory: .
